import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "components/Navbar";
import Footer from "components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@250;400&display=swap"
        rel="stylesheet"
      />

      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
